### ISSUE TITLE
How to "refit" on new data with new xreg?

### ISSUE THREAD

**Issue by vspinu** [gsucarrat/garchx#3]
I cannot find an easy way to get fitted conditional variance on new series.  `generics` package has a `refit` generic for this purpose. `fable` package uses it [extensively](https://fable.tidyverts.org/reference/refit.ARIMA.html) for its models. 

How can achieve similar one step ahead prediction with garchx?  

To give more context. I am fiting an arimax with fable package and garch on it's residuals with garchx. Then on the test dataset I get one step forecast with `refit`, then take residuals and want to get conditional variance at each step.

**Comment by gsucarrat** [comment]
Could you be more explicit of what you have in mind?

**Comment by gsucarrat** [comment]
So, to check my understanding, you want the vector s2 in the following code, right?:

  set.seed(123) #for reproducibility
  tmp <- garchxSim(200) 
  x <- tmp[1:100]
  x2 <- tmp[101:200]
  mod1 <- garchx(x)
  fit1 <- fitted(mod1)
  mod2 <- garchx(c(x,x2))
  fit2 <- fitted(mod2)
  s2 <- fit2[101:200]

**Comment by vspinu** [comment]
Not quite. I want at least `fitted(mod1, x2)`. Aka use parameters of mod1 estimated on x1 to calculate conditional variance on x2. But ideally I would want to have conditional variance one step ahead. In other words, compute conditional variance at step `i` based on the model estimated on previous `i-1` values, but much more efficient than directly re-estimating the model at every step. Does this make sense?

**Comment by gsucarrat** [comment]
I think the best thing would be if you wrote a code snippet of what you want:) Once I have a clear idea of what you want, then we can see if/how it can be included into the package. Note in that regard that you might be using the term "one-step-ahead" somewhat differently than in the statistical/forecasting literature. I think you might be referring to "recursive" estimation rather than "one-step-ahead" forecast. Here is an example (OLS-estimates) from another package I am involved in:

```
library(gets)
y <- rnorm(50)
mymod <- arx(y, ar=1:3) #ols-estimated ar(3)-model
recursive(mymod, from=10, plot=TRUE) #recursive parameter estimation

```

**Comment by vspinu** [comment]
>  I think you might be referring to "recursive" estimation rather than "one-step-ahead" forecast. 

To my mind recursive estimation of sigma2 on an out of sample observation N+1 is the "one-step-ahead" forecast of conditional variance. Sorry if it's not the correct terminology. 

What I want is very simple.  Fit on X[1:N] and predict (refit, recurse estimate, whatever the name is) sigma2 on X[N+1]. More generally fit model on X1 and then use this model to get fitted values of sigma2 on new data X2.

**Comment by gsucarrat** [comment]
Note that, for a GARCH model fitted to data X[1:N], there is no need for new data to generate the one-step-ahead (N+1) forecast of the conditional variance. Here is an example:
```
set.seed(123)
y <- garchxSim(1000)
mymod <- garchx(y)
predict(mymod, n.ahead=1)
```
I looked at the refit functions of the package fable, and it is not clear to me for what purpose one would like to use it. It appears to me that refit() does things that is already provided by predict() and fitted(), and/or by simple coding involving these. Could you provide an example where refit() is useful?

**Comment by gsucarrat** [comment]
I have made a basic prototype version of `refit.garchx()`:
```
refit.garchx <- function(object, newy=NULL, newxreg=NULL, ...)
{
  ##check:
  if( is.null(newy)){ stop("'newy' cannot be NULL") }
  if( !is.null(object$xreg) && is.null(newxreg) ){
    stop("'newxreg' is missing")
  }

  ##splice data:
  y <- c(object$y.coredata, coredata(as.zoo(newy)))
  if( is.null(newxreg) ){
    xregArg <- NULL
  }else{
    xregArg <- rbind(object$xreg, newxreg)
  }
  
  ##obtain spec:    
  archArg <- object$arch
  garchArg <- object$garch 
  asymArg <- object$asym

  ##refit:
  result <- garchx(y, arch=archArg, garch=garchArg, asym=asymArg,
      xreg=xregArg)
    
  ##return result:
  return(result)
}
```
Is this (more or less) what you want? Here is an example of its usage:
```
set.seed(123)
x <- matrix(rnorm(50*2), 50, 2)
y <- garchxSim(50)
mymod <- garchx(y, xreg=x)

newy <- rnorm(10)
newxreg <- matrix(rnorm(10*2), 10, 2)

newfit <- refit.garchx(mymod, newy, newxreg)
fitted(newfit) #1-step forecast of new fit
```

**Comment by vspinu** [comment]
>  It appears to me that refit() does things that is already provided by predict() and fitted(), and/or by simple coding involving these. 

If I understand correctly `refit` takes the model parameters, applies to new stream of data without re-estimation, and then can be used to predict further even after the new data. 

The docs are sparse:
  https://tidyverts.github.io/tidy-forecasting-principles/methods.html#re-estimation
  https://github.com/tidyverts/fable/issues/43

```
##refit:
  result <- garchx(y, arch=archArg, garch=garchArg, asym=asymArg,
      xreg=xregArg)
```

This part is not doing re-estimation, or does it?


```
mymod <- garchx(y)
predict(mymod, n.ahead=1)
```

Judging from the code it uses simuation for the prediction. I wonder if there is a direct, more efficient method to compute the mean prediction. I am hunting sigma2hat though. 

My understanding of the theory is that the last element of`fitted(model)` should give the "predicted" conditional variance for N+1 already. In other words, the estimated conditional variance sigma2hat[N] is already "one step ahead", as it is an estimate of sigma2[N+1] which is a variance conditional on state of the world as know at time N. Is this correct?

**Comment by gsucarrat** [comment]
I looked at the `refit.ARIMA()` function, and there re-estimation is optional with default `FALSE`. So I added a similar argument with default `FALSE` to the `refit.garchx()` function. The new version of the function is available here:

[https://github.com/gsucarrat/garchx/blob/master/refit.garchx.R](url)

Here is some code that illustrates its usage:
```
set.seed(123)
mX <- matrix(rnorm(30*2)^2, 30, 2)
vY <- garchxSim(30)
mymod <- garchx(vY, xreg=mX)

newy=rnorm(10)
newxreg=matrix(rnorm(10*2)^2, 10, 2)

newmod <- refit.garchx(mymod, newy, newxreg)
```
You can check that the coefficients and covariance are identical (that is, that no estimation has taken place) with coef(mymod)==coef(newmod) and vcov(mymod)==vcov(newmod). 

If my understanding is correct, what you are after (the 1-step conditional variance forecasts) are obtained as
`fitted(newmod) #the 10 last observations are new`
Finally, note that predict.garchx() can be applied on newmod:
`predict(newmod, n.ahead=5, newxreg=matrix(0,5,2))`
Re-estimation is not undertaken, but simulation is required if `n.ahead > 1`. Closed-form formulas exists for simple cases, but not for all the cases accommodated by the `garchx()` function. This is why parametric-bootstrap simulation is used instead when `n.ahead > 1`.
 
Is `refit.garchx()` approaching what you had in mind?

**Comment by gsucarrat** [comment]
> My understanding of the theory is that the last element offitted(model) should give the "predicted" conditional variance for N+1 already. In other words, the estimated conditional variance sigma2hat[N] is already "one step ahead", as it is an estimate of sigma2[N+1] which is a variance conditional on state of the world as know at time N. Is this correct?

**Comment by vspinu** [comment]
> Is refit.garchx() approaching what you had in mind?

Yes. That's exactly what I had in mind. Thanks a lot for fixing this. I am no longer working with the problem that I had back then when I reported it, but I will get back soon and will start playing with garchx again. Will report back if I have any issues. 

One last question is concerning this line: https://github.com/gsucarrat/garchx/blob/master/refit.garchx.R#L10

The implicit assumption is that the new data is immediately following the training sample. This need not be the case in general though.

**Comment by gsucarrat** [comment]
> Yes. That's exactly what I had in mind. Thanks a lot for fixing this. I am no longer working with the problem that I had back then when I reported it, but I will get back soon and will start playing with garchx again. Will report back if I have any issues.

Thumbs up!

> The implicit assumption is that the new data is immediately following the training sample. This need not be the case in general though.

The idea that the new data need not follow the "training sample" (frequently called "in-sample" as opposed to the "out-of-sample" in the forecasting literature) is related to what is known as k-fold validation. For static data, k-fold validation makes a lot of sense, since observations are usually independent (albeit heterogenous) from each other. In dynamic data, by contrast, where observations at t may depend heavily on the past - as in the GARCH model, it is not equally straightforward. This is why, in the forecast literature, the "out-of-sample" (i.e. the "test" sample) is almost invariably subsequent in time to the "in-sample" (i.e. the "training" sample). If the `refit()` function within the `fable` universe is typically used for cross validation purposes, then `refit.garchx()` has not been put together in a suitable way.

**Comment by vspinu** [comment]
> In dynamic data, by contrast, where observations at t may depend heavily on the past - as in the GARCH model, it is not equally straightforward.

Sure, but it's a meaningful exercise. I think it makes sense to be able to train on, say, last half of the sample and keep the first half as out-of sample. 

Another meaningful scenario is a cross-sectional out-of-sample. With two similar processes, one can train on one process, and backtest on another.

**Comment by gsucarrat** [comment]
> Sure, but it's a meaningful exercise. I think it makes sense to be able to train on, say, last half of the sample and keep the first half as out-of sample.

The idea is appealing, even in time series data, the problem is that implementation is more delicate. Consider, for example the GARCH(1,1) specification s2(t) = w + a e2(t-1) + b s2(t-1). To initiate the recursion you need a starting value on s2(t-1). If the out-of-sample is subsequent in time, then the natural initial recursion value is the last in-sample fitted s2. If not subsequent in time, then the initial recursion value has to be chosen. By default, i.e. when the `backcast.values` argument is `NULL`, then the `garchx()` function uses the sample average of e2. This makes sense from a theoretical point of view. From a forecasting point of view, however, this is not right, since you are using future values/information to initiate a recursion that starts in the past.

Anyways, to accomodate all this I have changed the `refit.garchx()` function. The "refit" is now exclusively on the new data - albeit the coefficient estimates and covariances of the old data are applied on the new data, and I have added a new argument, `backcast.values`, to accommodate the initial recursion value issue.

Could you have a new quick look at the function to see if behaves more closely to what is expected of the users of `refit()` methods?

**Comment by vspinu** [comment]
@gsucarrat I think what you have implemented is matching the intent of the `refit`. I haven't used the `fable` package much myself, so cannot judge. Once I am back to the conditional variance project I will report back. For now I think the issue has been completely addressed. 

Thanks a bunch for all the work!!!
